type Education {
  id: String!
  organization: String!
  city: String!
  state: String!
  degree: String!
  monthStart: Int!
  yearStart: Int!
  monthEnd: Int
  yearEnd: Int
  order: Int!
  image: String!
  desc: [String]!
  style: Style!
  createdAt: Time!
  updatedAt: Time!
}

input EducationInput {
  organization: String!,
  city: String!,
  state: String!,
  degree: String!,
  monthStart: Int!
  yearStart: Int!
  monthEnd: Int
  yearEnd: Int
  order: Int!,
  image: String!,
  desc: [String]!
}