type Education {
  _id: String
  organization: String
  city: String
  state: String
  degree: String
  time: String
  order: Int
  image: String
  desc: [String]
  style: Style
  createdAt: Time
  updatedAt: Time
}

input EducationInput {
  organization: String,
  city: String,
  state: String,
  degree: String,
  time: String,
  order: Int,
  image: String,
  desc: [String]
}