type Education {
  id: String!
  school: String!
  city: String!
  state: String!
  degree: String!
  monthStart: Int!
  yearStart: Int!
  monthEnd: Int
  yearEnd: Int
  order: Int!
  logoURL: String!
  descriptions: [String]!
  style: Style!
  createdAt: Time!
  updatedAt: Time!
}

input EducationInput {
  school: String!,
  city: String!,
  state: String!,
  degree: String!,
  monthStart: Int!
  yearStart: Int!
  monthEnd: Int
  yearEnd: Int
  order: Int!,
  logoURL: String!,
  descriptions: [String]!
}