type Experience {
  _id: String
  organization: String
  city: String
  state: String
  title: String
  time: String
  order: Int
  image: String
  desc: [String]
  style: Style
  createdAt: Time
  updatedAt: Time
}