scalar Time

type Query {
  # Education
    allEducations: [Education]
    getEducationById(_id: String!): Education

    # Experience
    allExperiences: [Experience]
    getExperienceById(_id: String!): Experience

}

type Mutation {
  # Education
  addEducation(
    education: EducationInput!,
    style: StyleInput!
  ): Education

  deleteEducation(
    _id: String!,
    styleId: String!
  ): Education

  # Experience
  addExperience(
    experience: ExperienceInput!,
    style: StyleInput!
  ): Experience

  deleteExperience(
    _id: String!,
    styleId: String!
  ): Experience

  # Style
    updateStyle(
      _id: String!,
      style: StyleInput!
    ): Style
}