scalar Time

type Query {
  # Education
    allEducations: [Education]
    getEducationById(_id: String!): Education
}

type Mutation {
  # Education
  addEducation(
    education: EducationInput!,
    style: StyleInput!
  ): Education

  updateEducation(
    id: String!,
    education: EducationInput!,
  ): Education

  deleteEducation(
    id: String!,
    styleId: String!
  ): Education

  # Style
    updateStyle(
      id: String!,
      style: StyleInput!
    ): Style
}