scalar Time

type Query {
  # Education
    allEducations: [Education]
    getEducationById(_id: String!): Education
}

type Mutation {
  # Education
  addEducation(
    education: EducationInput!,
    style: StyleInput!
  ): Education

  updateEducation(
    _id: String!,
    education: EducationInput!,
  ): Education

  deleteEducation(
    _id: String!,
    styleId: String!
  ): Education

  # Style
    updateStyle(
      _id: String!,
      style: StyleInput!
    ): Style
}