type Style {
  _id: String
  primaryColor: String
  secondaryColor: String
  bannerImage: String
  createdAt: Time
  updatedAt: Time
}

input StyleInput {
  primaryColor: String
  secondaryColor: String
  bannerImage: String
}