type Style {
  id: String
  primaryColor: String
  secondaryColor: String
  accentColor: String
  imageURL: String
}

input StyleInput {
  primaryColor: String
  secondaryColor: String
  accentColor: String
  imageURL: String
}